version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 458077315349.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ecr-demo .
      - docker tag ecr-demo:latest 458077315349.dkr.ecr.us-east-1.amazonaws.com/ecr-demo:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 458077315349.dkr.ecr.us-east-1.amazonaws.com/ecr-demo:latest